// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoz42ab5lrFubhnT5t7cywLAI7tTIOKNM',
    appId: '1:847953901005:web:82711573266c910d2a4084',
    messagingSenderId: '847953901005',
    projectId: 'tadarabapp-2e060',
    authDomain: 'tadarabapp-2e060.firebaseapp.com',
    storageBucket: 'tadarabapp-2e060.firebasestorage.app',
    measurementId: 'G-3F81XXWZYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ46qLKxkabd84Vj9d_uEqhHY8x2uiaC4',
    appId: '1:847953901005:android:ea2638611f2173f92a4084',
    messagingSenderId: '847953901005',
    projectId: 'tadarabapp-2e060',
    storageBucket: 'tadarabapp-2e060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSF4Q6jXNRPIB4fk8PkoRGLQ2rOJWpva8',
    appId: '1:847953901005:ios:b4d8bfcf76cb7f8d2a4084',
    messagingSenderId: '847953901005',
    projectId: 'tadarabapp-2e060',
    storageBucket: 'tadarabapp-2e060.firebasestorage.app',
    iosBundleId: 'com.example.tadarabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSF4Q6jXNRPIB4fk8PkoRGLQ2rOJWpva8',
    appId: '1:847953901005:ios:b4d8bfcf76cb7f8d2a4084',
    messagingSenderId: '847953901005',
    projectId: 'tadarabapp-2e060',
    storageBucket: 'tadarabapp-2e060.firebasestorage.app',
    iosBundleId: 'com.example.tadarabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoz42ab5lrFubhnT5t7cywLAI7tTIOKNM',
    appId: '1:847953901005:web:2cca9bbbd69a6f382a4084',
    messagingSenderId: '847953901005',
    projectId: 'tadarabapp-2e060',
    authDomain: 'tadarabapp-2e060.firebaseapp.com',
    storageBucket: 'tadarabapp-2e060.firebasestorage.app',
    measurementId: 'G-HC69G1HTYM',
  );
}
